create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  gold integer not null default 250 check (gold >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles
  add column if not exists role text not null default 'player',
  add column if not exists login_name text,
  add column if not exists login_email text;

alter table public.profiles
  drop constraint if exists profiles_role_check;

alter table public.profiles
  add constraint profiles_role_check
  check (role in ('player', 'admin'));

create unique index if not exists profiles_login_name_key
on public.profiles (login_name)
where login_name is not null;

create unique index if not exists profiles_login_email_key
on public.profiles (login_email)
where login_email is not null;

create table if not exists public.shop_items (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null,
  price integer not null check (price >= 0),
  accent_color text not null default '#8be7ff',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  item_id bigint not null references public.shop_items (id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, item_id)
);

create table if not exists public.purchase_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  item_id bigint not null references public.shop_items (id) on delete cascade,
  price_paid integer not null check (price_paid >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.shop_items enable row level security;
alter table public.inventory enable row level security;
alter table public.purchase_log enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "shop_items_read_all" on public.shop_items;
create policy "shop_items_read_all"
on public.shop_items
for select
to anon, authenticated
using (true);

drop policy if exists "inventory_select_own" on public.inventory;
create policy "inventory_select_own"
on public.inventory
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "purchase_log_select_own" on public.purchase_log;
create policy "purchase_log_select_own"
on public.purchase_log
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.buy_shop_item(p_user_id uuid, p_item_id bigint)
returns table (
  item_id bigint,
  item_name text,
  gold integer,
  quantity integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_price integer;
  v_name text;
  v_gold integer;
  v_quantity integer;
begin
  select price, name
  into v_price, v_name
  from public.shop_items
  where id = p_item_id;

  if not found then
    raise exception 'This shop item does not exist.';
  end if;

  select gold
  into v_gold
  from public.profiles
  where id = p_user_id
  for update;

  if not found then
    raise exception 'This player profile does not exist yet.';
  end if;

  if v_gold < v_price then
    raise exception 'Not enough gold for this purchase.';
  end if;

  update public.profiles
  set gold = gold - v_price
  where id = p_user_id
  returning profiles.gold into v_gold;

  insert into public.inventory (user_id, item_id, quantity)
  values (p_user_id, p_item_id, 1)
  on conflict (user_id, item_id)
  do update set quantity = public.inventory.quantity + 1
  returning inventory.quantity into v_quantity;

  insert into public.purchase_log (user_id, item_id, price_paid)
  values (p_user_id, p_item_id, v_price);

  return query
  select p_item_id, v_name, v_gold, v_quantity;
end;
$$;

revoke all on function public.buy_shop_item(uuid, bigint) from public, anon, authenticated;
grant execute on function public.buy_shop_item(uuid, bigint) to service_role;

insert into public.shop_items (slug, name, description, price, accent_color)
values
  ('starter-food', 'Starter Food', 'A simple pellet pack that keeps the fish tank busy.', 25, '#80d7ff'),
  ('coral-cave', 'Coral Cave', 'A bright coral shelter for the lower side of the tank.', 70, '#ff8f73'),
  ('moon-jelly', 'Moon Jelly', 'A soft jellyfish companion that adds a glowing accent.', 110, '#bdb2ff')
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  accent_color = excluded.accent_color;
