export const OLD_TESTAMENT_BOOKS = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  '1 Samuel',
  '2 Samuel',
  '1 Kings',
  '2 Kings',
  '1 Chronicles',
  '2 Chronicles',
  'Ezra',
  'Nehemiah',
  'Esther',
  'Job',
  'Psalms',
  'Proverbs',
  'Ecclesiastes',
  'Song of Solomon',
  'Isaiah',
  'Jeremiah',
  'Lamentations',
  'Ezekiel',
  'Daniel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi',
]

export const NEW_TESTAMENT_BOOKS = [
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrews',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation',
]

export const OLD_TESTAMENT_CATEGORIES = [
  {
    id: 'law',
    label: 'Law',
    books: OLD_TESTAMENT_BOOKS.slice(0, 5),
  },
  {
    id: 'history',
    label: 'History',
    books: OLD_TESTAMENT_BOOKS.slice(5, 17),
  },
  {
    id: 'poetry',
    label: 'Poetry',
    books: OLD_TESTAMENT_BOOKS.slice(17, 22),
  },
  {
    id: 'major-prophets',
    label: 'Major Prophets',
    books: OLD_TESTAMENT_BOOKS.slice(22, 27),
  },
  {
    id: 'minor-prophets',
    label: 'Minor Prophets',
    books: OLD_TESTAMENT_BOOKS.slice(27),
  },
]

export function getOldTestamentCategoryId(book) {
  return OLD_TESTAMENT_CATEGORIES.find((category) => category.books.includes(book))?.id ?? ''
}

export const TESTAMENTS = [
  {
    id: 'old',
    label: 'Old Testament',
    books: OLD_TESTAMENT_BOOKS,
  },
  {
    id: 'new',
    label: 'New Testament',
    books: NEW_TESTAMENT_BOOKS,
  },
]
